project:
  type: website
  output-dir: docs
  resources:
    - google3b856b0b4c437423.html

website:
  title: "Kun (Amanda) Bu"
  site-url: "https://kunppbu.github.io/kunbu.github.io/"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: News
        href: news.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true